#+HUGO_BASE_DIR: ../
#+TITLE: Expression
# #+DATE: 2020-03-19
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: English
#+HUGO_CATEGORIES: Study
#+HUGO_DRAFT: false

* Words
- =Amenable= : 
 - willing to accept or be influenced by a suggestion;
 - 意为顺从的，愿意接受建议的，耳朵软的之类的意思。在 OpenFlow 一文中，作者将 Amenable 放在句首，来表达需要实现的功能。
#+begin_quote
/Amenable to high-performance and low-cost implementations./
#+end_quote

- =sophisticated=
  - having a good understanding of the way people behave and/or a good knowledge of culture and fashion:
  - intelligent or made in a complicated way and therefore able to do complicated tasks:
  - 意为复杂精巧的，精于世故的，精通的，富有经验的。此处来形容功能精细复杂的东西。
#+begin_quote
One can also imagine more sophisticated controllers that dynamically add/remove ﬂows as an experiment progresses.
#+end_quote

- =envisage=
  - to imagine or expect something in the future, especially something good;
  - 想象，设想，用来描述技术的前景
#+begin_quote
One could envisage an extension to Ethane in which a policy dictates that particular ﬂows are sent to a user’s process in a controller, hence allowing researcher-speciﬁc processing to be performed in the network.
#+end_quote


* Sentences
- =更不用说=
#+begin_quote
Commercial switches and routers =do not= typically provide an open software platform, =let alone= provide a means to virtualize either their hardware or software.
#+end_quote

- =长期看来前景很不错= /（现在没啥用）/
#+begin_quote
=This approach is promising in the long-term=, but for the time being is targeted at large switching centers and is too expensive for widespread deployment in college wiring closets.
#+end_quote
