#+HUGO_BASE_DIR: ../
#+TITLE: Expression
# #+DATE: 2020-03-19
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: English
#+HUGO_CATEGORIES: Study
#+HUGO_DRAFT: false

* Words
- =mitigate=
  - 减轻
#+begin_quote
One of the important goals of data center networks is to avoid or =mitigate= the effect of network bottlenecks on the operation of the computing services offered
#+end_quote
- =diversified=
  - 多变化的，各种的
#+begin_quote
By using specialized optimization algorithms and =diversified= configuration options.
#+end_quote
- =seamless=
  - smoothly and continuously, with no apparent gaps or spaces between one part and the next
  - 无缝衔接的，平滑的
#+begin_quote
the load balancing service can take the appropriate actions to =seamlessly= distribute the traffic among the available servers.
#+end_quote
- =paramount=
  - more important than anything else;
  - 至关重要的
#+begin_quote
Another aspect of =paramount= importance is the portability of the programming language.
#+end_quote

- =Amenable= : 
  - willing to accept or be influenced by a suggestion;
  - 意为顺从的，愿意接受建议的，耳朵软的之类的意思。在 OpenFlow 一文中，作者将 Amenable 放在句首，来表达需要实现的功能。
#+begin_quote
=Amenable= to high-performance and low-cost implementations.
#+end_quote

- =sophisticated=
  - having a good understanding of the way people behave and/or a good knowledge of culture and fashion:
  - intelligent or made in a complicated way and therefore able to do complicated tasks:
  - 意为复杂精巧的，精于世故的，精通的，富有经验的。此处来形容功能精细复杂的东西。
#+begin_quote
One can also imagine more =sophisticated= controllers that dynamically add/remove ﬂows as an experiment progresses.
#+end_quote

- =envisage=
  - to imagine or expect something in the future, especially something good;
  - 想象，设想，用来描述技术的前景
#+begin_quote
One could =envisage= an extension to Ethane in which a policy dictates that particular ﬂows are sent to a user’s process in a controller, hence allowing researcher-speciﬁc processing to be performed in the network.
#+end_quote

- =inertia=
  - lack of activity or interest, or unwillingness to make an effort to do anything
  - 惰性、惯性、懒惰。作者用来表述某个东西难以推动发展
#+begin_quote
Due to the =inertia= of current IP networks, a new routing protocol can take five to ten years to be fully designed, evaluated, and deployed.
#+end_quote

- =alleviate=
  - to make something bad such as pain or problems less severe
  - 减轻某种痛苦，减轻，缓和，使镇定

- =proliferate=
  - to increase a lot and suddenly in number
  - 激增、增殖，作者用来表达大量东西涌现，也就是激增的含义。
#+begin_quote
To =alleviate= the lack of in-path functionalities within the network, a *myriad* of specialized components and middleboxes, such as firewalls, intrusion detection systems, and deep packet inspection engines, =proliferate= in current networks.
#+end_quote

- =ubiquitous=
  - seeming to be everywhere 
  - 到处存在的
    #+begin_quote
  abstractions are essential tools of research in computer science and information technology, being already an =ubiquitous= feature of many computer architectures and systems.
    #+end_quote

- =anchor=
  - to lower an anchor into the water in order to stop a boat from moving away;
  - to make something or someone stay in one position by fastening him, her, or it firmly;
  - 锚状物、固定、支撑，赖以支撑的人、物。作者用来表达一个技术依赖于一些东西（这些东西可以避免）
#+begin_quote
However, these technologies are anchored on a box-by-box basis configuration.
#+end_quote

- =analogy= 
  - 相似，类似，类比
  - 翻译说是举例来说，我感觉说是类比来看也可以：
#+begin_quote
The base network service functions are what we consider the essential functionality all controllers should provide. =As an analogy=, these functions are like base services of operating systems, such as program execution, input/output (I/O) operations control, communications, protection, and so on.
#+end_quote

* Sentences
- =同时=
#+begin_quote
for instance, allowing the distribution and directing of large groups of client requests without requiring controller intervention for every new flow. =In tandem=, operation in reactive mode may still be used when traffic bursts are detected.
#+end_quote
- =更不用说=
#+begin_quote
Commercial switches and routers =do not= typically provide an open software platform, =let alone= provide a means to virtualize either their hardware or software.
#+end_quote

- =长期看来前景很不错= /（现在没啥用）/
#+begin_quote
=This approach is promising in the long-term=, but for the time being is targeted at large switching centers and is too expensive for widespread deployment in college wiring closets.
#+end_quote

- =来满足=
#+begin_quote
Programming languages can also provide specialized abstractions =to cope with= other management requirements, such as monitoring.
#+end_quote


* Professional Expression
- =fine-grained <==> coarser grained= 细粒度，粗粒度；
- =race-free= 非竞争的；
- =single point of failure=  单点故障；
- =heterogeneity= 异质性；
- =Wrapping Up Remarks= 总结，结束语；
- =introduce= 引入，提出。 

* Good Sentences 
#+begin_quote
The controller application *needs* to monitor the network traffic *and* use some sort of threshold *in* the flow counters *to* redistribute clients *among* the servers *when* bottlenecks are likely to happen.
#+end_quote

